### ISSUE TITLE
Reference Request

### ISSUE THREAD

**Issue by jwangjie** [tomzhu0225/vehicle-performance-simulation-via-matlab#1]
Hi @tomzhu0225 ,

Thank you for creating and sharing this valuable data for vehicle performance tests. I planned to use one of them, WLTP, in my own research. I wonder if you can share some reference papers for me to cite so you can get your deserved credit. 

Regards,
Jie

**Comment by tomzhu0225** [comment]
Thank you for reaching out and expressing interest in using the WLTP data from my GitHub repository for your research. I appreciate your consideration for proper citation.

To clarify, this project was originally developed a few years ago as part of a course project, in collaboration with a major European car company. Consequently, there are no formal reference papers associated with the data (such as engine power/fuel mapping, etc.).

However, the code available in the repository is authored by me. If you wish to cite the repository in your research, you may use the following citation format:
```
@misc{vehicle_performance_simulation,
    author = {Bowen ZHU},
    title = {Vehicle Performance Simulation via MATLAB},
    year = {2022},
    url = {https://github.com/tomzhu0225/vehicle-performance-simulation-via-matlab}
}
```
Best regards,
Bowen ZHU

**Comment by tomzhu0225** [comment]
I added a citation file, maybe it is easier for you.

**Comment by jwangjie** [comment]
Thank you for your quick response, @tomzhu0225, appreciate it. //Jie
